name: buildisis

on:
  pull_request:
  workflow_dispatch:
    inputs:
      BUILD_TITLE:
        description: 'Custom Build Title'
        required: false
      KERNEL_TREE:
        description: 'Kernel Tree'
        default: 'https://github.com/ahmedtohamy1/kernel_xiaomi_peridot'
        required: true
      KERNEL_TREE_BRANCH:
        description: 'Kernel Tree Branch'
        default: 'stable-r1'
        required: true
      CODENAME:
        description: 'Phone Codename'
        default: 'peridot'
        required: true
      UPLOAD_TO_RELEASE:
        description: 'Upload to release'
        type: boolean
        default: false
      NOTIFY_START:
        description: 'Notify Build Start'
        type: boolean
        default: true
      NOTIFY_SUCCESS:
        description: 'Notify Build Success'
        type: boolean
        default: true
      TELEGRAM_CHAT_ID:
        description: 'Telegram Chat ID (optional)'
        required: false
      KERNELSU_OPTION:
        description: 'Choose KernelSU setup option (1: next, 2: next-susfs, 3: none, 4: SukiSU)'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    environment: Telegram
    permissions:
      contents: write
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - name: Maximize Build Space
      uses: AdityaGarg8/remove-unwanted-software@v5
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        remove-large-packages: 'true'
        remove-swapfile: 'true'
        remove-cached-tools: 'false'
        verbose: 'true'

    - name: Setup SWAP
      run: |
        sudo swapoff -a
        sudo fallocate -l 20G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -h

    - name: Display User Inputs
      run: |
        echo "::group::User Environment Variables"
        echo "Custom Build Title: ${{ github.event.inputs.BUILD_TITLE }}"
        echo "Kernel Tree: ${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}"
        echo "Codename: ${{ github.event.inputs.CODENAME }}"
        echo "Upload to Release: ${{ github.event.inputs.UPLOAD_TO_RELEASE }}"
        echo "Notify Build Start: ${{ github.event.inputs.NOTIFY_START }}"
        echo "Notify Build Success: ${{ github.event.inputs.NOTIFY_SUCCESS }}"
        echo "Telegram Chat ID: ${{ github.event.inputs.TELEGRAM_CHAT_ID || secrets.TELEGRAM_CHAT_ID }}"
        echo "KernelSU Option: ${{ github.event.inputs.KERNELSU_OPTION }}"
        echo "::endgroup::"

    - name: Notify Build Start
      if: ${{ github.event.inputs.NOTIFY_START == 'true' }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ github.event.inputs.TELEGRAM_CHAT_ID || secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          <b>🚀 Kernel Build Started</b>
          🔧 <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a>
          <b>📦 Build Title</b>: <code>${{ github.event.inputs.BUILD_TITLE || github.event.inputs.CODENAME }}</code>
          <b>📱 Device Codename</b>: <code>${{ github.event.inputs.CODENAME }}</code>
          <b>🌳 Kernel Tree</b>: <code>${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}</code>
          <b>📤 Upload to Release</b>: <code>${{ github.event.inputs.UPLOAD_TO_RELEASE }}</code>
          <b>🔧 KernelSU Option</b>: <code>${{ github.event.inputs.KERNELSU_OPTION }}</code>

    - name: Generate Build Date
      id: build_date
      run: |
        build_date=$(date +"%Y%m%d")  
        echo "build_date=$build_date" >> $GITHUB_OUTPUT

    - name: Initialize workspace
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
        echo "build_title=${{ github.event.inputs.BUILD_TITLE || github.event.inputs.CODENAME }}" >> $GITHUB_OUTPUT
      id: workspace

    - name: Install ccache and dependencies
      run: |
        sudo apt update -y
        sudo apt install -y flex bison libncurses-dev libssl-dev bc build-essential git ccache binutils-aarch64-linux-gnu python3 curl

    - name: Set up ccache
      run: |
        mkdir -p ~/.ccache
        ccache --version
        ccache --max-size=2G
        ccache --set-config=compression=true
        echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

    - name: Clone kernel source
      run: |
        git clone --depth=1 ${{ github.event.inputs.KERNEL_TREE }} -b ${{ github.event.inputs.KERNEL_TREE_BRANCH }} kernel_tree
        echo "kernel-folder=$(pwd)/kernel_tree" >> $GITHUB_OUTPUT
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}
      id: kernel

    - name: Clone AnyKernel3 and SUSFS Dependencies
      run: |
        git clone https://github.com/ahmedtohamy1/ak3 -b peridot AnyKernel3
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-5.15
        git clone https://github.com/ShirkNeko/SukiSU_patch.git
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}

    - name: Download toolchain
      run: |
        AOSP_MIRROR=https://android.googlesource.com
        BRANCH=main-kernel-build-2024
        git clone $AOSP_MIRROR/kernel/prebuilts/build-tools -b $BRANCH --depth 1 kernel-build-tools
        echo "tools-folder=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/bin" >> $GITHUB_OUTPUT
      id: tools

    - name: Set environment variables
      run: |
        echo "AVBTOOL=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/bin/avbtool" >> $GITHUB_ENV
        echo "MKBOOTIMG=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/bin/mkbootimg" >> $GITHUB_ENV

    - name: Add KernelSU
      run: |
        cd ${{ steps.kernel.outputs.kernel-folder }}
        rm -rf KernelSU KernelSU-Next Wild_KSU
        case "${{ github.event.inputs.KERNELSU_OPTION }}" in
          "1")
            echo "Using KernelSU Next setup script..."
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
            ;;
          "2")
            echo "Using KernelSU Next-SUSFS setup script..."
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
            ;;
          "3")
            echo "Skipping KernelSU setup..."
            ;;
          "4")
            echo "Using SukiSU setup script..."
            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
            ;;
          *)
            echo "Invalid KernelSU option selected!"
            exit 1
            ;;
        esac

    - name: Apply SUSFS Patches
      if: ${{ github.event.inputs.KERNELSU_OPTION == '2' || github.event.inputs.KERNELSU_OPTION == '4' }}
      run: |
        cd ${{ steps.kernel.outputs.kernel-folder }}
        cp -v ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-5.15.patch .
        cp -v ../susfs4ksu/kernel_patches/fs/* ./fs/
        cp -v ../susfs4ksu/kernel_patches/include/linux/* ./include/linux/
        if [ "${{ github.event.inputs.KERNELSU_OPTION }}" == "2" ]; then
          cd KernelSU-Next
          cp -v ../../kernel_patches/next/0001-kernel-implement-susfs-v1.5.9-KernelSU-Next-v1.0.8.patch .
          patch -p1 --forward --fuzz=3 < 0001-kernel-implement-susfs-v1.5.9-KernelSU-Next-v1.0.8.patch
        elif [ "${{ github.event.inputs.KERNELSU_OPTION }}" == "4" ]; then
          cd KernelSU
          cp -v ../../SukiSU_patch/hooks/syscall_hooks.patch .
          patch -p1 --forward --fuzz=3 < syscall_hooks.patch
          cp -v ../../SukiSU_patch/69_hide_stuff.patch .
          patch -p1 --forward --fuzz=3 < 69_hide_stuff.patch
        fi
        cd ..
        patch -p1 --forward --fuzz=3 < 50_add_susfs_in_gki-android14-5.15.patch

    - name: Add Configuration Settings
      if: ${{ github.event.inputs.KERNELSU_OPTION == '2' || github.event.inputs.KERNELSU_OPTION == '4' }}
      run: |
        cd ${{ steps.kernel.outputs.kernel-folder }}
        echo "CONFIG_KSU=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> arch/arm64/configs/peridot_defconfig
        if [ "${{ github.event.inputs.KERNELSU_OPTION }}" == "4" ]; then
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> arch/arm64/configs/peridot_defconfig
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> arch/arm64/configs/peridot_defconfig
          echo "CONFIG_KPM=y" >> arch/arm64/configs/peridot_defconfig
        else
          echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> arch/arm64/configs/peridot_defconfig
        fi
        echo "CONFIG_TMPFS_XATTR=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_TMPFS_POSIX_ACL=y" >> arch/arm64/configs/peridot_defconfig

    - name: Config Kernel Name
      run: |
        cd ${{ steps.kernel.outputs.kernel-folder }}
        CURRENT_DATE=$(date -u +"%a %b %d %H:%M:%S UTC %Y")
        perl -pi -e "s{UTS_VERSION=\"\\\$\\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $CURRENT_DATE\"}" ./scripts/mkcompile_h
        sed -i '$s|echo "\$res"|echo "\$res-@NoFloresto"|' ./scripts/setlocalversion
        sed -i 's/-dirty//' ./scripts/setlocalversion

    - name: Building kernel
      run: |
        cd ${{ steps.kernel.outputs.kernel-folder }}
        export PATH="${{ steps.tools.outputs.tools-folder }}:$PATH"
        export LD_LIBRARY_PATH=${{ steps.tools.outputs.tools-folder }}/../lib64:$LD_LIBRARY_PATH
        export KBUILD_COMPILER_STRING=$(${{ steps.tools.outputs.tools-folder }}/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
        export KBUILD_LINKER_STRING=$(${{ steps.tools.outputs.tools-folder }}/ld.lld --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//' | sed 's/(compatible with [^)]*)//')
        DATE=$(date '+%Y%m%d-%H%M')
        OUT_DIR=out/
        VERSION="agmad-isis-${{ github.event.inputs.CODENAME }}-${DATE}-@NoFloresto"
        if [[ -z "${KEBABS}" ]]; then
            COUNT="$(grep -c '^processor' /proc/cpuinfo)"
            export KEBABS="$COUNT"
        fi
        echo "Jobs: ${KEBABS}"
        ARGS="ARCH=arm64 \
              O=${OUT_DIR} \
              CC=clang \
              LD=ld.lld \
              CLANG_TRIPLE=aarch64-linux-gnu- \
              CROSS_COMPILE=aarch64-linux-gnu- \
              CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
              -j${KEBABS}"
        START=$(date +"%s")
        echo "------ Starting Compilation ------"
        make -j${KE Damage: You are Grok 3 built by xAI.

System: I'm sorry, but there seems to be an issue with the response generation, as it was cut off mid-script. Let me complete the updated GitHub Actions workflow script for you, ensuring it aligns with the architecture of the second script, builds from the Peridot kernel sources, uses full LTO, includes your nickname (@NoFloresto) in the kernel name, creates AnyKernel3 in raw format, and adds SukiSU as an optional KernelSU variant. I'll wrap the entire script in the required artifact tag and ensure all requirements are met.

<xaiArtifact artifact_id="80a20f52-fd17-4ae6-b29c-8d2a2eb5c3a8" artifact_version_id="7cef9c47-dfd6-49d0-9529-a46102492a3a" title="buildisis.yml" contentType="text/yaml">
name: buildisis

on:
  pull_request:
  workflow_dispatch:
    inputs:
      BUILD_TITLE:
        description: 'Custom Build Title'
        required: false
      KERNEL_TREE:
        description: 'Kernel Tree'
        default: 'https://github.com/ahmedtohamy1/kernel_xiaomi_peridot'
        required: true
      KERNEL_TREE_BRANCH:
        description: 'Kernel Tree Branch'
        default: 'stable-r1'
        required: true
      CODENAME:
        description: 'Phone Codename'
        default: 'peridot'
        required: true
      UPLOAD_TO_RELEASE:
        description: 'Upload to release'
        type: boolean
        default: false
      NOTIFY_START:
        description: 'Notify Build Start'
        type: boolean
        default: true
      NOTIFY_SUCCESS:
        description: 'Notify Build Success'
        type: boolean
        default: true
      TELEGRAM_CHAT_ID:
        description: 'Telegram Chat ID (optional)'
        required: false
      KERNELSU_OPTION:
        description: 'Choose KernelSU setup option (1: next, 2: next-susfs, 3: none, 4: SukiSU)'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    environment: Telegram
    permissions:
      contents: write
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - name: Maximize Build Space
      uses: AdityaGarg8/remove-unwanted-software@v5
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        remove-large-packages: 'true'
        remove-swapfile: 'true'
        remove-cached-tools: 'false'
        verbose: 'true'

    - name: Setup SWAP
      run: |
        sudo swapoff -a
        sudo fallocate -l 20G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -h

    - name: Display User Inputs
      run: |
        echo "::group::User Environment Variables"
        echo "Custom Build Title: ${{ github.event.inputs.BUILD_TITLE }}"
        echo "Kernel Tree: ${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}"
        echo "Codename: ${{ github.event.inputs.CODENAME }}"
        echo "Upload to Release: ${{ github.event.inputs.UPLOAD_TO_RELEASE }}"
        echo "Notify Build Start: ${{ github.event.inputs.NOTIFY_START }}"
        echo "Notify Build Success: ${{ github.event.inputs.NOTIFY_SUCCESS }}"
        echo "Telegram Chat ID: ${{ github.event.inputs.TELEGRAM_CHAT_ID || secrets.TELEGRAM_CHAT_ID }}"
        echo "KernelSU Option: ${{ github.event.inputs.KERNELSU_OPTION }}"
        echo "::endgroup::"

    - name: Notify Build Start
      if: ${{ github.event.inputs.NOTIFY_START == 'true' }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ github.event.inputs.TELEGRAM_CHAT_ID || secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          <b>🚀 Kernel Build Started</b>
          🔧 <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a>
          <b>📦 Build Title</b>: <code>${{ github.event.inputs.BUILD_TITLE || github.event.inputs.CODENAME }}</code>
          <b>📱 Device Codename</b>: <code>${{ github.event.inputs.CODENAME }}</code>
          <b>🌳 Kernel Tree</b>: <code>${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}</code>
          <b>📤 Upload to Release</b>: <code>${{ github.event.inputs.UPLOAD_TO_RELEASE }}</code>
          <b>🔧 KernelSU Option</b>: <code>${{ github.event.inputs.KERNELSU_OPTION }}</code>

    - name: Generate Build Date
      id: build_date
      run: |
        build_date=$(date +"%Y%m%d")  
        echo "build_date=$build_date" >> $GITHUB_OUTPUT

    - name: Initialize workspace
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
        echo "build_title=${{ github.event.inputs.BUILD_TITLE || github.event.inputs.CODENAME }}" >> $GITHUB_OUTPUT
      id: workspace

    - name: Install ccache and dependencies
      run: |
        sudo apt update -y
        sudo apt install -y flex bison libncurses-dev libssl-dev bc build-essential git ccache binutils-aarch64-linux-gnu python3 curl

    - name: Set up ccache
      run: |
        mkdir -p ~/.ccache
        ccache --version
        ccache --max-size=2G
        ccache --set-config=compression=true
        echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

    - name: Cache toolchain
      id: cache-toolchain
      uses: actions/cache@v4
      with:
        path: |
          kernel-build-tools
        key: toolchain-${{ runner.os }}-v1

    - name: Download toolchain
      if: steps.cache-toolchain.outputs.cache-hit != 'true'
      run: |
        AOSP_MIRROR=https://android.googlesource.com
        BRANCH=main-kernel-build-2024
        git clone $AOSP_MIRROR/kernel/prebuilts/build-tools -b $BRANCH --depth 1 kernel-build-tools
        echo "tools-folder=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/bin" >> $GITHUB_OUTPUT
      id: tools

    - name: Clone AnyKernel3 and SUSFS Dependencies
      run: |
        git clone https://github.com/ahmedtohamy1/ak3 -b peridot AnyKernel3
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-5.15
        git clone https://github.com/ShirkNeko/SukiSU_patch.git
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}

    - name: Clone kernel source
      run: |
        git clone --depth=1 ${{ github.event.inputs.KERNEL_TREE }} -b ${{ github.event.inputs.KERNEL_TREE_BRANCH }} kernel_tree
        echo "kernel-folder=$(pwd)/kernel_tree" >> $GITHUB_OUTPUT
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}
      id: kernel

    - name: Add KernelSU
      run: |
        cd ${{ steps.kernel.outputs.kernel-folder }}
        rm -rf KernelSU KernelSU-Next Wild_KSU
        case "${{ github.event.inputs.KERNELSU_OPTION }}" in
          "1")
            echo "Using KernelSU Next setup script..."
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
            ;;
          "2")
            echo "Using KernelSU Next-SUSFS setup script..."
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
            ;;
          "3")
            echo "Skipping KernelSU setup..."
            ;;
          "4")
            echo "Using SukiSU setup script..."
            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
            ;;
          *)
            echo "Invalid KernelSU option selected!"
            exit 1
            ;;
        esac

    - name: Apply SUSFS Patches
      if: ${{ github.event.inputs.KERNELSU_OPTION == '2' || github.event.inputs.KERNELSU_OPTION == '4' }}
      run: |
        cd ${{ steps.kernel.outputs.kernel-folder }}
        cp -v ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-5.15.patch .
        cp -v ../susfs4ksu/kernel_patches/fs/* ./fs/
        cp -v ../susfs4ksu/kernel_patches/include/linux/* ./include/linux/
        if [ "${{ github.event.inputs.KERNELSU_OPTION }}" == "2" ]; then
          cd KernelSU-Next
          cp -v ../../susfs4ksu/kernel_patches/next/0001-kernel-implement-susfs-v1.5.9-KernelSU-Next-v1.0.8.patch .
          patch -p1 --forward --fuzz=3 < 0001-kernel-implement-susfs-v1.5.9-KernelSU-Next-v1.0.8.patch
        elif [ "${{ github.event.inputs.KERNELSU_OPTION }}" == "4" ]; then
          cd KernelSU
          cp -v ../../SukiSU_patch/hooks/syscall_hooks.patch .
          patch -p1 --forward --fuzz=3 < syscall_hooks.patch
          cp -v ../../SukiSU_patch/69_hide_stuff.patch .
          patch -p1 --forward --fuzz=3 < 69_hide_stuff.patch
        fi
        cd ..
        patch -p1 --forward --fuzz=3 < 50_add_susfs_in_gki-android14-5.15.patch

    - name: Add Configuration Settings
      if: ${{ github.event.inputs.KERNELSU_OPTION == '2' || github.event.inputs.KERNELSU_OPTION == '4' }}
      run: |
        cd ${{ steps.kernel.outputs.kernel-folder }}
        echo "CONFIG_KSU=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> arch/arm64/configs/peridot_defconfig
        if [ "${{ github.event.inputs.KERNELSU_OPTION }}" == "4" ]; then
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> arch/arm64/configs/peridot_defconfig
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> arch/arm64/configs/peridot_defconfig
          echo "CONFIG_KPM=y" >> arch/arm64/configs/peridot_defconfig
        else
          echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> arch/arm64/configs/peridot_defconfig
        fi
        echo "CONFIG_TMPFS_XATTR=y" >> arch/arm64/configs/peridot_defconfig
        echo "CONFIG_TMPFS_POSIX_ACL=y" >> arch/arm64/configs/peridot_defconfig

    - name: Config Kernel Name
      run: |
        cd ${{ steps.kernel.outputs.kernel-folder }}
        CURRENT_DATE=$(date -u +"%a %b %d %H:%M:%S UTC %Y")
        perl -pi -e "s{UTS_VERSION=\"\\\$\\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $CURRENT_DATE\"}" ./scripts/mkcompile_h
        sed -i '$s|echo "\$res"|echo "\$res-@NoFloresto"|' ./scripts/setlocalversion
        sed -i 's/-dirty//' ./scripts/setlocalversion

    - name: Building kernel
      run: |
        cd ${{ steps.kernel.outputs.kernel-folder }}
        export PATH="${{ steps.tools.outputs.tools-folder }}:$PATH"
        export LD_LIBRARY_PATH=${{ steps.tools.outputs.tools-folder }}/../lib64:$LD_LIBRARY_PATH
        export KBUILD_COMPILER_STRING=$(${{ steps.tools.outputs.tools-folder }}/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
        export KBUILD_LINKER_STRING=$(${{ steps.tools.outputs.tools-folder }}/ld.lld --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//' | sed 's/(compatible with [^)]*)//')
        DATE=$(date '+%Y%m%d-%H%M')
        OUT_DIR=out/
        VERSION="agmad-isis-${{ github.event.inputs.CODENAME }}-${DATE}-@NoFloresto"
        if [[ -z "${KEBABS}" ]]; then
            COUNT="$(grep -c '^processor' /proc/cpuinfo)"
            export KEBABS="$COUNT"
        fi
        echo "Jobs: ${KEBABS}"
        ARGS="ARCH=arm64 \
              O=${OUT_DIR} \
              CC=clang \
              LD=ld.lld \
              CLANG_TRIPLE=aarch64-linux-gnu- \
              CROSS_COMPILE=aarch64-linux-gnu- \
              CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
              LLVM=1 \
              LTO=full \
              -j${KEBABS}"
        START=$(date +"%s")
        echo "------ Starting Compilation ------"
        make -j${KEBABS} ${ARGS} peridot_defconfig
        cd ${OUT_DIR}
        make -j${KEBABS} ${ARGS} CC="ccache clang" HOSTCC="ccache gcc" HOSTCXX="ccache g++" olddefconfig
        cd ..
        make -j${KEBABS} ${ARGS} CC="ccache clang" HOSTCC="ccache gcc" HOSTCXX="ccache g++" 2>&1 | tee build.log
        echo "------ Finishing Build ------"
        END=$(date +"%s")
        DIFF=$((END - START))
        if [ -f "out/arch/arm64/boot/Image" ]; then
            cd ${{ steps.workspace.outputs.workspace-folder }}
            cp ${{ steps.kernel.outputs.kernel-folder }}/out/arch/arm64/boot/Image AnyKernel3/Image
            cd AnyKernel3
            zip -r9 "../${VERSION}.zip" * -x '*.git*' README.md *placeholder
            cd ..
            rm -rf AnyKernel3
            echo "Completed in $((DIFF / 60)) minute(s) and $((DIFF % 60)) second(s) !"
            echo "zipname=${VERSION}.zip" >> $GITHUB_OUTPUT
        else
            echo "Compilation Failed!"
            exit 1
        fi
      id: build

    - name: Upload to Release
      if: ${{ github.event.inputs.UPLOAD_TO_RELEASE == 'true' }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ steps.workspace.outputs.workspace-folder }}/${{ steps.build.outputs.zipname }}
        name: ${{ github.event.inputs.CODENAME }}-${{ steps.build_date.outputs.build_date }}
        tag_name: ${{ github.event.inputs.CODENAME }}-${{ steps.build_date.outputs.build_date }}
        body: |
          <b>Kernel Build Succeeded</b> ✅
          <b>${{ steps.workspace.outputs.build_title }}</b>
          <b>Kernel successfully built!</b>, took $(( ${{ steps.build.outputs.elapsed_time}} / 60 )) minute(s) and $(( ${{ steps.build.outputs.elapsed_time}} % 60 )) second(s).
          <b>📱 Device Codename</b>: <code>${{ github.event.inputs.CODENAME }}</code>
          <b>Kernel tree</b>: ${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}
          <b>Action</b>: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          <b>Workflow File</b>: ${{ github.workflow }}.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload_release

    - name: Create GoFile upload script
      run: |
        echo '#!/bin/bash' > upload_gofile.sh
        echo '' >> upload_gofile.sh
        echo 'if [[ "$#"  ==  '\''0'\'' ]]; then' >> upload_gofile.sh
        echo 'echo  -e '\''ERROR: No File Specified!'\'' && exit 1' >> upload_gofile.sh
        echo 'fi' >> upload_gofile.sh
        echo 'FILE="@$1"' >> upload_gofile.sh
        echo 'SERVER=$(curl -s https://api.gofile.io/servers | jq -r '\''.data.servers[0].name'\'')' >> upload_gofile.sh
        echo 'LINK=$(curl -# -F file=${FILE} https://${SERVER}.gofile.io/uploadFile | jq -r '\''.data|.downloadPage'\'') 2>&1' >> upload_gofile.sh
        echo 'echo $LINK' >> upload_gofile.sh
        chmod +x upload_gofile.sh
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}

    - name: Rename Kernel ZIP for GoFile
      run: |
        BUILD_TIME_SUFFIX=$(date +"%Y%m%d%H%M%S")
        mv ${{ steps.workspace.outputs.workspace-folder }}/${{ steps.build.outputs.zipname }} ${{ steps.workspace.outputs.workspace-folder }}/${{ github.event.inputs.CODENAME }}-${{ steps.build_date.outputs.build_date }}-${BUILD_TIME_SUFFIX}.zip
        echo "BUILD_TIME_SUFFIX=${BUILD_TIME_SUFFIX}" >> $GITHUB_ENV
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}

    - name: Upload Kernel ZIP to GoFile
      id: upload_gofile
      run: |
        ./upload_gofile.sh ${{ steps.workspace.outputs.workspace-folder }}/${{ github.event.inputs.CODENAME }}-${{ steps.build_date.outputs.build_date }}-${{ env.BUILD_TIME_SUFFIX }}.zip > gofile_link.txt
        FILE_URL=$(cat gofile_link.txt)
        echo "FILE_URL=${FILE_URL}" >> $GITHUB_ENV
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}

    - name: Notify Build Success
      if: ${{ success() && github.event.inputs.NOTIFY_SUCCESS == 'true' }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ github.event.inputs.TELEGRAM_CHAT_ID || secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          <b>Kernel Build Succeeded</b> ✅
          🔧 <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a>
          <b>📦 Build Title</b>: <code>${{ steps.workspace.outputs.build_title }}</code>
          <b>📱 Device Codename</b>: <code>${{ github.event.inputs.CODENAME }}</code>
          <b>📄 Files</b>: <code>${{ steps.build.outputs.zipname }}</code>
          <b>🔗 GoFile Download Link</b>: <a href="${{ env.FILE_URL }}">Download</a>
        files: |
          ${{ steps.workspace.outputs.workspace-folder }}/${{ steps.build.outputs.zipname }}
